apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: errohit07/product-service
          ports:
            - containerPort: 5003

          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/amazona
