services:
  frontend:
    image: errohit07/frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    image: errohit07/user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona
      - PORT=5001


  order-service:
    image: errohit07/order-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona
      - PORT=5002


  product-service:
    image: errohit07/product-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona
      - PORT=5003

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

