version: "3.8"

services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build: ./backend/services/user-service
    image: user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona


  order-service:
    build: ./backend/services/order-service
    image: order-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona


  product-service:
    build: ./backend/services/product-service
    image: product-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/amazona

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

