name: Shopping app

on: 
  push:
    branches:
      - main

jobs:
  Image-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}


      - name: Build Docker image (Frontend)
        run: docker build -t errohit07/frontend ./frontend

      - name: Push image (frontend)
        run: docker push errohit07/frontend

      - name: Build Docker image (User Service)
        run: docker build -t errohit07/user-service ./backend/services/user-service

      - name: Push image (user service)
        run: docker push errohit07/user-service

      - name: Build Docker image (Order Service)
        run: docker build -t errohit07/order-service ./backend/services/order-service

      - name: Push image (order service)
        run: docker push errohit07/order-service

      - name: Build Docker image (Product Service)
        run: docker build -t errohit07/product-service ./backend/services/product-service

      - name: Push image (product service)
        run: docker push errohit07/product-service

      - name: Pull on EC2 instance 
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          envs: IMAGE_TAG
          script: |
            echo "Using IMAGE_TAG=$IMAGE_TAG"

            cd /home/ec2-user/shopping
            git pull origin main
            docker-compose pull
            docker-compose up -d
<<<<<<< HEAD

=======
>>>>>>> parent of 10380ab (Kubeadm config start)
            

            kubectl --kubeconfig=/home/ec2-user/.kube/config get nodes
            kubectl --kubeconfig=/home/ec2-user/.kube/config apply -f k8s/ --recursive
<<<<<<< HEAD
=======
            kubectl --kubeconfig=/home/ec2-user/.kube/config apply rollout restart deployment frontend
>>>>>>> parent of efb8135 (Kubeadm config start)

            kubectl set image deployment/frontend frontend-container=errohit07/frontend:${IMAGE_TAG}
            kubectl set image deployment/user-service user-service-container=errohit07/user-service:${IMAGE_TAG}
            kubectl set image deployment/product-service product-service-container=errohit07/product-service:${IMAGE_TAG}
            kubectl set image deployment/order-service order-service-container=errohit07/order-service:${IMAGE_TAG}

            kubectl --kubeconfig=/home/ec2-user/.kube/config rollout restart deployment